- name: Verify apache installation
  hosts: all
  user: opc
  become: yes
  gather_facts: yes
  vars:
    http_port: 80
    max_clients: 200
  tasks:
  - name: Ensure apache is at the latest version
    ansible.builtin.yum:
      name: httpd
      state: latest

  - name: Write the index.html
    ansible.builtin.template:
      src: index.html
      dest: /var/www/html/
    notify:
    - Restart apache

  - name: Ensure apache is running
    ansible.builtin.service:
      name: httpd
      state: started

  handlers:
    - name: Restart apache
      ansible.builtin.service:
        name: httpd
        state: restarted
