- name: Loops, conditions and Register
  hosts: all
  user: opc
  tasks:
    - name: Add several users
      yum:
        name: "{{ item }}"
        state: present
      loop:
       - telnet
       - httpd
