- name: Loops, conditions and Register
  hosts: all
  user: opc
  become: yes
  tasks:
    - name: Adding packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
       - telnet
       - httpd
      when: ansible_os_family == "Redhat"
