- name: Using bucket for latest html storage
  hosts: all
  user: opc
  become: yes
  tasks:
    - name: Install httpd
      dnf:
        name: httpd
        state: present
    - name: Create a new customer secret key
      oci_customer_secret_key:
        user_id: "{{ oci_id }}"
        name: "my first customer secret key"
 
    - name: Get/download an object to dest
      oci_object_storage_object_facts:
        namespace_name: axwm1yvro9yu
        bucket_name: jdk_storage
        object_name: newone.html
        dest: /var/www/html
        
    - name: Check httpd service
      service:
        name: httpd
        state: restarted
    
        
