- name: tags
  hosts: all
  user: opc
  become: yes
  tasks:
    - name: Install ntp
      ansible.builtin.yum:
        name: ntp
        state: present
      tags: ntp

    - name: Enable and run ntpd
      ansible.builtin.service:
        name: ntpd
        state: started
        enabled: yes
      tags: ntp

    - name: Install NFS utils
      ansible.builtin.yum:
        name:
        - nfs-utils
        - nfs-util-lib
        state: present
      tags: filesharing
